services:
  - type: web
    name: roledogs-api
    env: node
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: cd services/api && npm install
    # explicit start – bind to $PORT
    startCommand: cd services/api && PORT=$PORT npm start
    autoDeploy: true
    healthCheckPath: /health

  - type: worker
    name: roledogs-worker
    env: node
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: cd services/worker && npm install
    startCommand: cd services/worker && node worker.js
    autoDeploy: true

  - type: web
    name: roledogs-keycloak
    env: docker
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    # override the default; run container on $PORT
    startCommand: docker run --rm -p $PORT:8080 roledogs-keycloak
    autoDeploy: true

databases:
  - name: roledogs-db
    engine: postgres
    plan: free
