services:
  - type: web
    name: roledogs-api
    environment: node
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: cd services/api && npm install
    startCommand: cd services/api && npm start
    autoDeploy: true

  - type: worker
    name: roledogs-worker
    environment: node
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: cd services/worker && npm install
    startCommand: cd services/worker && node worker.js
    autoDeploy: true

  - type: web
    name: roledogs-keycloak
    environment: docker
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: docker build -f services/keycloak/Dockerfile -t roledogs-keycloak .
    startCommand: docker run -p 8080:8080 roledogs-keycloak
    autoDeploy: true

databases:
  - name: roledogs-db
    engine: postgres
    plan: free
