# render.yaml

services:
  - type: web
    name: roledogs-api
    env: node
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: npm install --prefix services/api
    startCommand: npm run start --prefix services/api
    autoDeploy: true
    envVars:
      - key: POSTGRES_URL
        value: ${{ databases.roledogs-db.connectionString }}

  - type: worker
    name: roledogs-worker
    env: node
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: npm install --prefix services/worker
    startCommand: node services/worker/worker.js
    autoDeploy: true
    envVars:
      - key: POSTGRES_URL
        value: ${{ databases.roledogs-db.connectionString }}
      - key: MINIO_ENDPOINT
        value: https://roledogs.onrender.com/minio

  - type: web
    name: roledogs-keycloak
    env: docker
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    dockerfilePath: services/keycloak/Dockerfile
    startCommand: java -jar /opt/keycloak/keycloak.jar start-dev
    autoDeploy: true
    envVars:
      - key: KC_ADMIN_USER
        value: admin
      - key: KC_ADMIN_PASSWORD
        value: admin

databases:
  - name: roledogs-db
    engine: postgres
    plan: free
