services:
  - type: web
    name: roledogs-api
    env: node
    region: ord
    branch: main
    repo: https://github.com/mmiholdings/roledogs.git
    buildCommand: |
      # upgrade pip, increase timeout, disable cache
      python -m pip install --upgrade pip
      pip install --default-timeout=100 --no-cache-dir -r requirements.txt
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: RENDER_URL
        value: https://roledogs.onrender.com
      - key: KEYCLOAK_BASE
        value: https://roledogs.onrender.com/keycloak
      - key: POSTGRES_URL
        value: ${{ databases.roledogs-db.connectionString }}

  # …same change for any other Python services, e.g. docs site…
