version: "3.9"
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: changeme
    volumes: [pgdata:/var/lib/postgresql/data]
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  api:
    build: ../services/api
    environment:
      - REDIS_HOST=redis
    depends_on: [redis, postgres]
    ports: ["4000:4000"]
volumes:
  pgdata:
