name: Backend Fly
on:
  push:
    paths-ignore: ["frontend/**"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api, worker, keycloak]
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@v1
        with:
          args: "deploy --app roledogs-${{ matrix.service }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
