credentials:
  usernames:
    admin:
      email: admin@genie.ai
      name: Admin User
      password: 'pbkdf2:sha256:260000$example$hash'  # Placeholder hash
cookie:
  name: genie_dashboard
  key: some_secret_key
  expiry_days: 1