
name: Run GENIE Weekly Intelligence Sweep

on:
  schedule:
    - cron: "0 12 * * 0"  # Every Sunday at 12 PM UTC

jobs:
  weekly-audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GENIE Repo
      uses: actions/checkout@v3

    - name: Run Inference Router
      run: python3 live_inference_router.py --claude 0.72 --predictnow 0.63 --marl 0.65

    - name: Run Agent Tracker
      run: python3 agent_memory_tracker.py

    - name: Run GPT Trade Review
      run: python3 post_trade_gpt_review.py

    - name: Run Agent Weight Builder
      run: python3 weight_config_builder.py --mo 0.35 --reggie 0.3 --ace 0.35
