
name: GENIE CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Deps
        run: |
          pip install -r requirements.txt
      - name: Run GENIE Scheduler
        run: |
          nohup python3 scheduler.py &
