services:
  - type: web
    name: genie-feedback-api
    env: python
    buildCommand: ""
    startCommand: "python3 genie_feedback_api.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: genie-dashboard
    env: python
    buildCommand: ""
    startCommand: "streamlit run streamlit_audit_dashboard.py"
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 8501